name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Make light and dark variants
        run: |
          cp src/pages/index.js src/pages/light.js
          cp src/pages/index.js src/pages/dark.js
          cd docs
          sed '2 s/creating-bundles/creating-bundles-light/' creating-bundles.md > creating-bundles-light.md
          sed '2 s/creating-bundles/creating-bundles-dark/' creating-bundles.md > creating-bundles-dark.md
      - name: Build
        run: npm run build
      - name: Theme fixup
        run: |
          cd build
          mv light/index.html light.html
          mv dark/index.html dark.html
          rmdir light
          rmdir dark
      - name: Lighthouse CI
        run: |
          export LHCI_BUILD_CONTEXT__CURRENT_BRANCH=${GITHUB_REF##*/}
          export LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG=${GITHUB_REPOSITORY}
          npx @lhci/cli@^0.3.0 autorun
        env:
          LHCI_GITHUB_TOKEN: ${{ github.token }}
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          npx gh-pages@3 \
            --dist build \
            --repo https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git \
            --user "GitHub Action <actions@github.com>"
